# -*- coding: utf-8 -*-
"""MovieRecommender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QKWp-FZWJr1j7MP8eiUdNKrg_nnWIbIa
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

column_names = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('ratings.csv', names=column_names)

df.head

movie_titles = pd.read_csv("movie_titles.csv")
movie_titles.head

df = pd.merge(df,movie_titles, on='item_id')
df.head

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
sns.set_style('white')
# %matplotlib inline

df.groupby('title')['rating'].mean().sort_values(ascending=False).head()

df.groupby('title')['rating'].count().sort_values(ascending=False).head()

df.groupby('title')['rating'].mean().sort_values(ascending=False).head()

ratings = pd.DataFrame(df.groupby('title')['rating'].mean())
ratings.head()

ratings['num of ratings'] = pd.DataFrame(df.groupby('title')['rating'].count())
ratings.head()

plt.figure(figsize=(10,4))
ratings['num of ratings'].hist(bins=70, range=(30,200))

plt.figure(figsize=(10,4))
ratings['rating'].hist(bins=70)

moviemat = df.pivot_table(index='user_id', columns='title', values='rating')
moviemat.head()

pulpfiction_user_ratings = moviemat['Pulp Fiction (1994)']
pulpfiction_user_ratings.head()

similar_to_pulpfiction = moviemat.corrwith(pulpfiction_user_ratings)

corr_pulpfiction = pd.DataFrame(similar_to_pulpfiction, columns=['Correlation'])
corr_pulpfiction.dropna(inplace=True)
corr_pulpfiction.head()

corr_pulpfiction.sort_values('Correlation', ascending=False).head(10)

corr_pulpfiction = corr_pulpfiction.join(ratings['num of ratings'])
corr_pulpfiction.head()

corr_pulpfiction[corr_pulpfiction['num of ratings']>80].sort_values('Correlation', ascending=False).head()